#!/usr/bin/env python

"""
demo database writer
"""

from FunkyBusFare.dbwriter import VehiclePositionsETL

if __name__ == "__main__": 
    VEHPOS = "http://developer.go-metro.com/TMGTFSRealTimeWebService/vehicle/VehiclePositions.pb"
    streamwriter = VehiclePositionsETL(VEHPOS, "sqlite:///test.db")
    streamwriter.write()
