#!/usr/bin/env python

import requests
from google.protobuf import json_format
from google.transit import gtfs_realtime_pb2
from FunkyBusFare.protobuf_to_dict import protobuf_to_dict
from FunkyBusFare.flattery import flatten

def vehicle_position(path):
    response = requests.get(path)
    feed = gtfs_realtime_pb2.FeedMessage()
    feed.ParseFromString(response.content)
    for entity in feed.entity:
        foo = protobuf_to_dict(entity)
        print(flatten(foo))

if __name__ == "__main__":
    VEHPOS = "http://developer.go-metro.com/TMGTFSRealTimeWebService/vehicle/VehiclePositions.pb"
    vehicle_position(VEHPOS)
