#!/usr/bin/env python

from FunkyBusFare.streamwriter import StreamWriter

if __name__ == "__main__": 
    VEHPOS = "http://developer.go-metro.com/TMGTFSRealTimeWebService/vehicle/VehiclePositions.pb"
    streamwriter = StreamWriter(VEHPOS, "./records",)
    streamwriter.write()
